common:
    controller:
        class_prefix:        \Kneub\Controllers\
        method_suffix:       Action

    db:
        driver:       pgsql
        charset:      utf8
        collation:    utf8_general_ci
        prefix:       null
