credentials:
    jwt:
        secret_api:          as2-F%d7Esk8@18Dspq6,bix
    db:
        database:     qsweb
        username:     kneub
        password:     as2dfg
    ged.picker:
        url: https://ged-picker.botalista-dev.ch/
    uid.generator:
        url: https://uid-generator.botalista-dev.ch/
