apiVersion: v1
kind: Secret
metadata:
  name: bota-ani-secret
  namespace: test-app
type: Opaque
stringData:
  jwt.secret_api: as2-F%d7Esk8@18Dspq6,bix
  db.database: qsweb
  db.username: kneub
  db.password: as2dfg
  ged.picker.url: https://ged-picker.botalista-dev.ch/
  uid.generator.url: https://uid-generator.botalista-dev.ch/

  # spring.datasource.host: "//test-app-postgres"
  # spring.datasource.port: "5432"
  # spring.datasource.database: "test-app"
  # spring.datasource.username: "toto"
  # spring.datasource.password: "titi"
