apiVersion: v1
kind: Secret
metadata:
  name: bota-ani-secret
  namespace: test-app
type: Opaque
stringData:
  spring.datasource.host: "//test-app-postgres"
  spring.datasource.port: "5432"
  spring.datasource.database: "test-app"
  spring.datasource.username: "toto"
  spring.datasource.password: "titi"
