apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-app-ingress
  namespace: test-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host:
    http:
      paths:
      - path: /test-app
        backend:
          serviceName: test-app-service
          servicePort: http
