apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  namespace: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        date: DATE_DEPLOYMENT
        stage: BRANCH_NAME
    spec:
      volumes:
      - name: bota-ani-credentials
        emptyDir: { }
      - name: foo
        configMap:
          name: myconfigmap
      initContainers:
      - name: confd-init
        image: node79989-cjb-private-registry.hidora.com:5000/bota-ani-confd:DEPLOY_COMMIT_HASH
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 15Mi
          limits:
            cpu: 500m
            memory: 30Mi
        env:
        - name: JWT_SECRETAPI
          valueFrom:
            secretKeyRef:
              name: bota-ani-secret
              key: jwt.secretapi
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bota-ani-secret
              key: db.database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bota-ani-secret
              key: db.username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bota-ani-secret
              key: db.password
        - name: GED_PICKER_URL
          valueFrom:
            secretKeyRef:
              name: bota-ani-secret
              key: ged.picker.url
        - name: UID_GENERATOR_URL
          valueFrom:
            secretKeyRef:
              name: bota-ani-secret
              key: uid.generator.url
        volumeMounts:
        - name: bota-ani-credentials
          mountPath: /app/credentials
      containers:
      - name: test-app-container
        image: node79989-cjb-private-registry.hidora.com:5000/testapp:DEPLOY_COMMIT_HASH
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: bota-ani-credentials
          mountPath: "/var/www/html/app/config2"
        - name: foo
          mountPath: "/var/www/html/app/config2/myconf.yaml"
          subPath: config.yaml
          readOnly: true

        # testapp:latest
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 1
