[template]
src = "credentials.conf.tmpl"
dest = "/app/credentials/credentials.properties"
keys = [
    "/spring/datasource/host",
    "/spring/datasource/port",
    "/spring/datasource/database",
    "/spring/datasource/username",
    "/spring/datasource/password"
]
