[template]
src = "credentials.conf.tmpl"
dest = "/app/config/credentials2.yaml"
keys = [
    "/jwt/secretapi",
    "/db/database",
    "/db/username",
    "/db/password",
    "/ged/picker/url",
    "/uid/generator/url"
]
